### ISSUE TITLE
Provide support for Promise types

### ISSUE THREAD

**Issue by Risto-Stevcev** [plaid/sanctuary-def#49]
It's currently not supported:

```bash
TypeError: ‘I’ received [object Promise] as its first argument, but this value is not a member of any of the types in the environment:

  - (Array ???)
  - Boolean
  - Date
  ...
```

**Comment by davidchambers** [comment]
Thank you for the bug report, @Risto-Stevcev!

This was addressed in #38. I've spent the weekend preparing to release `sanctuary-def@0.5.0`. Once I've done so I'll open a pull request to resolve plaid/sanctuary#165. Once that has been merged I'll publish `sanctuary@0.10.0`.

**Comment by zhangchiqing** [comment]
Hi @davidchambers ,

It's not clear to me how Promise is supported in sanctuary-def@0.5.0. And I can't find it in [the API document](https://github.com/sanctuary-js/sanctuary-def) either. Do I miss anything?

Let's say I want to add type checks for the following `isGreaterThan10` function that takes a number and return a Promise that will be either resolved with a number or rejected with an error.
```
var isGreaterThan10 = function(num) {
  if (num > 10) {
    return Promise.resolve(true);
  } else {
    return Promise.reject(new Error('number ' + num + ' is not greater than 10));
  }
};
```

Is it possible to define types like this?
```
var isGreaterThan10 = def('isGreaterThan10', {}, [$.Number, $.Promise($.Boolean, $.Error)], function(num) {
  if (num > 10) {
    return Promise.resolve(true);
  } else {
    return Promise.reject(new Error('number ' + num + ' is not greater than 10));
  }
});
```

**Comment by davidchambers** [comment]
Before looking at the Promise type, let's consider the Either type. It's clearly a binary type. We may have a value of a type such as `Either a b` or `Either String Integer`. When using [`$.BinaryType`][1] we must provide an `Either a b -> Array a` function and an `Either a b -> Array b` function. For `Right(42)`, for example, the former would return `[]` (since there is no value of type `a`) and the latter would return `[42]`.

Given a value of type `Promise a b`, on the other hand, we may not be able to access an "inner" value at all. The "extractor" functions would likely both end up being `promise => []`, which is not very useful. It's therefore more honest to define the Promise type via [`$.NullaryType`][2]:

```javascript
//    PromiseType :: Type
const PromiseType = $.NullaryType('Promise', x => S.type(x) === 'Promise');
```

This is a scenario in which we lack type information at run time which would be available at compile time were JavaScript statically typed.


[1]: https://github.com/sanctuary-js/sanctuary-def#binarytype
[2]: https://github.com/sanctuary-js/sanctuary-def#nullarytype

**Comment by zhangchiqing** [comment]
Yeah, we are not able to access the "inner" value of a Promise given its asynchronous nature. 

Thanks @davidchambers for the workaround!
